repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.83.5
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
        exclude: examples/
        args:
        - --args=--fix

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
        exclude: README.md

  - repo: https://github.com/kabisa/terraform-datadog-pre-commit-hook
    rev: "1.3.6"
    hooks:
      - id: terraform-datadog-docs
        args:
        - "."
